### ISSUE TITLE
[feat] form에 따른 Question, Answer CRUD 구현 및 GPT 대답 구현

### ISSUE THREAD

**Issue by hsjni0110** [A-Interview/backend#10]
## :fire: 어떤 기능을 추가하신 건가요?

form에 따른 Question, Answer CRUD 구현하기

## :monocle_face: 주의할 점이 있나요? 

주석 잘 달아주세요..!

## :memo: 참고 사항

- 제목 양식을 지켜주세요.

- [타입] 간단한 제목

- 제목은 알아보기 쉽게 작성해 주세요!

**Comment by Tojaman** [comment]
git add . 하니깐 warning: in the working copy of 'speak_to_chat/migrations/0002_gptanswer.py', LF will be replaced by CRLF the next time Git touches it 오류 발생. 뭔지 모르겠지만 일단 push 했습니다.
